---
- name: Update and upgrade Ubuntu packages
  hosts: all
  become: yes
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600  # 1 hour

    - name: Upgrade all packages
      apt:
        upgrade: dist
